# Generated by Django 3.1.5 on 2021-01-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcoding',
            name='notes',
            field=models.TextField(blank=True, default='', verbose_name='Coding Notes'),
        ),
    ]
