# Generated by Django 3.1.5 on 2021-03-10 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_dot_test_can_be_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
