# Generated by Django 3.1.12 on 2021-11-12 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_update_test_dot_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={'ordering': ['name', 'year', 'grade_level']},
        ),
    ]
