name: Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Cache
        uses: actions/cache@v2.1.1
        with:
          path: .venv
          key: ${{ hashFiles('Pipfile.lock') }}
      - name: Install dependencies
        run: |
          sudo pip install pipenv
          PIPENV_VENV_IN_PROJECT=1 pipenv sync --dev
      - name: Linting and static analysis
        run: |
          pipenv run pre-commit run --all-files
      - name: Initialize DB
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres"
        run: |
          pipenv run python manage.py migrate
      - name: Run tests
        env:
          DATABASE_URL: "postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres"
        run: |
          pipenv run python manage.py test
